//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdHocMigrator.ExecuteSQLService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", ConfigurationName="ExecuteSQLService.VM_SQLQueries")]
    public interface VM_SQLQueries {
        
        // CODEGEN: Generating message contract since the wrapper name (ExecuteSQLQueryRequest) of message ExecuteSQLQueryRequest does not match the default value (ExecuteSQLQuery)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.virtuemart.net/VM_SQLQueries/ExecuteSQLQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        AdHocMigrator.ExecuteSQLService.ExecuteSQLQueryResponse ExecuteSQLQuery(AdHocMigrator.ExecuteSQLService.ExecuteSQLQueryRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ExecuteSQLSelectQueryRequest) of message ExecuteSQLSelectQueryRequest does not match the default value (ExecuteSQLSelectQuery)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.virtuemart.net/VM_SQLQueries/ExecuteSQLSelectQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        AdHocMigrator.ExecuteSQLService.ExecuteSQLSelectQueryResponse ExecuteSQLSelectQuery(AdHocMigrator.ExecuteSQLService.ExecuteSQLSelectQueryRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ExecuteSQLInsertQueryRequest) of message ExecuteSQLInsertQueryRequest does not match the default value (ExecuteSQLInsertQuery)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.virtuemart.net/VM_SQLQueries/ExecuteSQLInsertQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        AdHocMigrator.ExecuteSQLService.ExecuteSQLInsertQueryResponse ExecuteSQLInsertQuery(AdHocMigrator.ExecuteSQLService.ExecuteSQLInsertQueryRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ExecuteSQLUdpateQueryRequest) of message ExecuteSQLUpdateQueryRequest does not match the default value (ExecuteSQLUpdateQuery)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.virtuemart.net/VM_SQLQueries/ExecuteSQLUpdateQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        AdHocMigrator.ExecuteSQLService.ExecuteSQLUpdateQueryResponse ExecuteSQLUpdateQuery(AdHocMigrator.ExecuteSQLService.ExecuteSQLUpdateQueryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/")]
    public partial class loginInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/")]
    public partial class columnAndValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idxField;
        
        private string columnField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idx {
            get {
                return this.idxField;
            }
            set {
                this.idxField = value;
                this.RaisePropertyChanged("idx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
                this.RaisePropertyChanged("column");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/")]
    public partial class SQLResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private columnAndValue[] columnsAndValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public columnAndValue[] columnsAndValues {
            get {
                return this.columnsAndValuesField;
            }
            set {
                this.columnsAndValuesField = value;
                this.RaisePropertyChanged("columnsAndValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteSQLQueryRequest", WrapperNamespace="http://www.virtuemart.net/VM_SQLQueries/", IsWrapped=true)]
    public partial class ExecuteSQLQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdHocMigrator.ExecuteSQLService.loginInfo loginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sqlRequest;
        
        public ExecuteSQLQueryRequest() {
        }
        
        public ExecuteSQLQueryRequest(AdHocMigrator.ExecuteSQLService.loginInfo loginInfo, string sqlRequest) {
            this.loginInfo = loginInfo;
            this.sqlRequest = sqlRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteSQLQueryResponse", WrapperNamespace="http://www.virtuemart.net/VM_SQLQueries/", IsWrapped=true)]
    public partial class ExecuteSQLQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SQLResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SQLResult[] SQLResult;
        
        public ExecuteSQLQueryResponse() {
        }
        
        public ExecuteSQLQueryResponse(SQLResult[] SQLResult) {
            this.SQLResult = SQLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteSQLSelectQueryRequest", WrapperNamespace="http://www.virtuemart.net/VM_SQLQueries/", IsWrapped=true)]
    public partial class ExecuteSQLSelectQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdHocMigrator.ExecuteSQLService.loginInfo loginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string table;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string whereClause;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("column", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] columns;
        
        public ExecuteSQLSelectQueryRequest() {
        }
        
        public ExecuteSQLSelectQueryRequest(AdHocMigrator.ExecuteSQLService.loginInfo loginInfo, string table, string whereClause, string[] columns) {
            this.loginInfo = loginInfo;
            this.table = table;
            this.whereClause = whereClause;
            this.columns = columns;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteSQLSelectQueryResponse", WrapperNamespace="http://www.virtuemart.net/VM_SQLQueries/", IsWrapped=true)]
    public partial class ExecuteSQLSelectQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SQLResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SQLResult[] SQLResult;
        
        public ExecuteSQLSelectQueryResponse() {
        }
        
        public ExecuteSQLSelectQueryResponse(SQLResult[] SQLResult) {
            this.SQLResult = SQLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteSQLInsertQueryRequest", WrapperNamespace="http://www.virtuemart.net/VM_SQLQueries/", IsWrapped=true)]
    public partial class ExecuteSQLInsertQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdHocMigrator.ExecuteSQLService.loginInfo loginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string table;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string whereClause;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("column", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] columns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=4)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] values;
        
        public ExecuteSQLInsertQueryRequest() {
        }
        
        public ExecuteSQLInsertQueryRequest(AdHocMigrator.ExecuteSQLService.loginInfo loginInfo, string table, string whereClause, string[] columns, string[] values) {
            this.loginInfo = loginInfo;
            this.table = table;
            this.whereClause = whereClause;
            this.columns = columns;
            this.values = values;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteSQLInsertQueryResponse", WrapperNamespace="http://www.virtuemart.net/VM_SQLQueries/", IsWrapped=true)]
    public partial class ExecuteSQLInsertQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SQLResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SQLResult[] SQLResult;
        
        public ExecuteSQLInsertQueryResponse() {
        }
        
        public ExecuteSQLInsertQueryResponse(SQLResult[] SQLResult) {
            this.SQLResult = SQLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteSQLUdpateQueryRequest", WrapperNamespace="http://www.virtuemart.net/VM_SQLQueries/", IsWrapped=true)]
    public partial class ExecuteSQLUpdateQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdHocMigrator.ExecuteSQLService.loginInfo loginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string table;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string whereClause;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("column", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] columns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=4)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] values;
        
        public ExecuteSQLUpdateQueryRequest() {
        }
        
        public ExecuteSQLUpdateQueryRequest(AdHocMigrator.ExecuteSQLService.loginInfo loginInfo, string table, string whereClause, string[] columns, string[] values) {
            this.loginInfo = loginInfo;
            this.table = table;
            this.whereClause = whereClause;
            this.columns = columns;
            this.values = values;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteSQLUdpateQueryResponse", WrapperNamespace="http://www.virtuemart.net/VM_SQLQueries/", IsWrapped=true)]
    public partial class ExecuteSQLUpdateQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.virtuemart.net/VM_SQLQueries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SQLResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SQLResult[] SQLResult;
        
        public ExecuteSQLUpdateQueryResponse() {
        }
        
        public ExecuteSQLUpdateQueryResponse(SQLResult[] SQLResult) {
            this.SQLResult = SQLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VM_SQLQueriesChannel : AdHocMigrator.ExecuteSQLService.VM_SQLQueries, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VM_SQLQueriesClient : System.ServiceModel.ClientBase<AdHocMigrator.ExecuteSQLService.VM_SQLQueries>, AdHocMigrator.ExecuteSQLService.VM_SQLQueries {
        
        public VM_SQLQueriesClient() {
        }
        
        public VM_SQLQueriesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VM_SQLQueriesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VM_SQLQueriesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VM_SQLQueriesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdHocMigrator.ExecuteSQLService.ExecuteSQLQueryResponse AdHocMigrator.ExecuteSQLService.VM_SQLQueries.ExecuteSQLQuery(AdHocMigrator.ExecuteSQLService.ExecuteSQLQueryRequest request) {
            return base.Channel.ExecuteSQLQuery(request);
        }
        
        public SQLResult[] ExecuteSQLQuery(AdHocMigrator.ExecuteSQLService.loginInfo loginInfo, string sqlRequest) {
            AdHocMigrator.ExecuteSQLService.ExecuteSQLQueryRequest inValue = new AdHocMigrator.ExecuteSQLService.ExecuteSQLQueryRequest();
            inValue.loginInfo = loginInfo;
            inValue.sqlRequest = sqlRequest;
            AdHocMigrator.ExecuteSQLService.ExecuteSQLQueryResponse retVal = ((AdHocMigrator.ExecuteSQLService.VM_SQLQueries)(this)).ExecuteSQLQuery(inValue);
            return retVal.SQLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdHocMigrator.ExecuteSQLService.ExecuteSQLSelectQueryResponse AdHocMigrator.ExecuteSQLService.VM_SQLQueries.ExecuteSQLSelectQuery(AdHocMigrator.ExecuteSQLService.ExecuteSQLSelectQueryRequest request) {
            return base.Channel.ExecuteSQLSelectQuery(request);
        }
        
        public SQLResult[] ExecuteSQLSelectQuery(AdHocMigrator.ExecuteSQLService.loginInfo loginInfo, string table, string whereClause, string[] columns) {
            AdHocMigrator.ExecuteSQLService.ExecuteSQLSelectQueryRequest inValue = new AdHocMigrator.ExecuteSQLService.ExecuteSQLSelectQueryRequest();
            inValue.loginInfo = loginInfo;
            inValue.table = table;
            inValue.whereClause = whereClause;
            inValue.columns = columns;
            AdHocMigrator.ExecuteSQLService.ExecuteSQLSelectQueryResponse retVal = ((AdHocMigrator.ExecuteSQLService.VM_SQLQueries)(this)).ExecuteSQLSelectQuery(inValue);
            return retVal.SQLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdHocMigrator.ExecuteSQLService.ExecuteSQLInsertQueryResponse AdHocMigrator.ExecuteSQLService.VM_SQLQueries.ExecuteSQLInsertQuery(AdHocMigrator.ExecuteSQLService.ExecuteSQLInsertQueryRequest request) {
            return base.Channel.ExecuteSQLInsertQuery(request);
        }
        
        public SQLResult[] ExecuteSQLInsertQuery(AdHocMigrator.ExecuteSQLService.loginInfo loginInfo, string table, string whereClause, string[] columns, string[] values) {
            AdHocMigrator.ExecuteSQLService.ExecuteSQLInsertQueryRequest inValue = new AdHocMigrator.ExecuteSQLService.ExecuteSQLInsertQueryRequest();
            inValue.loginInfo = loginInfo;
            inValue.table = table;
            inValue.whereClause = whereClause;
            inValue.columns = columns;
            inValue.values = values;
            AdHocMigrator.ExecuteSQLService.ExecuteSQLInsertQueryResponse retVal = ((AdHocMigrator.ExecuteSQLService.VM_SQLQueries)(this)).ExecuteSQLInsertQuery(inValue);
            return retVal.SQLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdHocMigrator.ExecuteSQLService.ExecuteSQLUpdateQueryResponse AdHocMigrator.ExecuteSQLService.VM_SQLQueries.ExecuteSQLUpdateQuery(AdHocMigrator.ExecuteSQLService.ExecuteSQLUpdateQueryRequest request) {
            return base.Channel.ExecuteSQLUpdateQuery(request);
        }
        
        public SQLResult[] ExecuteSQLUpdateQuery(AdHocMigrator.ExecuteSQLService.loginInfo loginInfo, string table, string whereClause, string[] columns, string[] values) {
            AdHocMigrator.ExecuteSQLService.ExecuteSQLUpdateQueryRequest inValue = new AdHocMigrator.ExecuteSQLService.ExecuteSQLUpdateQueryRequest();
            inValue.loginInfo = loginInfo;
            inValue.table = table;
            inValue.whereClause = whereClause;
            inValue.columns = columns;
            inValue.values = values;
            AdHocMigrator.ExecuteSQLService.ExecuteSQLUpdateQueryResponse retVal = ((AdHocMigrator.ExecuteSQLService.VM_SQLQueries)(this)).ExecuteSQLUpdateQuery(inValue);
            return retVal.SQLResult;
        }
    }
}
